title: "My Portfolio"
description: "Welcome to my professional portfolio showcasing my work in AI, research, and more."
url: "https://trystine.github.io/Trishala_Ahalpara"
theme: jekyll-theme-cayman  # or replace with the name of your chosen theme
