title: "My Portfolio"
description: "Welcome! Researcher in Machine Learning and Data Science. I believe every data has a story and we are all just training to be better readers "
url: "https://trystine.github.io/Trishala_Ahalpara"
theme: jekyll-theme-cayman

header_pages:
  - index.md
  - about.md
  - projects.md
  - hobbies.md
  - current.md
