title: "My Portfolio"
description: "Applied AI Research Engineer · Generative AI · LLMs · RAG · Agentic AI"
url: "https://trystine.github.io/Trishala_Ahalpara"
theme: jekyll-theme-cayman

header_pages:
  - index.md
  - about.md
  - projects.md
  - hobbies.md
  - current.md
