title: "My Portfolio"
description: "Welcome to my professional portfolio showcasing my work in AI, research, and more."
url: "https://trystine.github.io/Trishala_Ahalpara"
theme: jekyll-theme-cayman 

header_pages:
  -README.md
  - index.md
  - about.md
  - projects.md
  - hobbies.md
  - current.md

